"""initial schema

Revision ID: 507931ac3cd5
Revises: 
Create Date: 2026-08-24 03:15:53.114584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507931ac3cd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('genres', sa.String(length=255), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id', 'media_type', name='uq_tmdb_id_media_type')
    )
    op.create_index(op.f('ix_titles_id'), 'titles', ['id'], unique=False)
    op.create_index(op.f('ix_titles_tmdb_id'), 'titles', ['tmdb_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('watch_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('watched_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'title_id', name='uq_user_title')
    )
    op.create_index(op.f('ix_watch_entries_id'), 'watch_entries', ['id'], unique=False)
    op.create_index(op.f('ix_watch_entries_title_id'), 'watch_entries', ['title_id'], unique=False)
    op.create_index(op.f('ix_watch_entries_user_id'), 'watch_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watch_entries_user_id'), table_name='watch_entries')
    op.drop_index(op.f('ix_watch_entries_title_id'), table_name='watch_entries')
    op.drop_index(op.f('ix_watch_entries_id'), table_name='watch_entries')
    op.drop_table('watch_entries')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_titles_tmdb_id'), table_name='titles')
    op.drop_index(op.f('ix_titles_id'), table_name='titles')
    op.drop_table('titles')
    # ### end Alembic commands ###
