"""add profile fields to user

Revision ID: e329ac50c6b4
Revises: 507931ac3cd5
Create Date: 2026-09-02 20:30:13.843626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e329ac50c6b4'
down_revision = '507931ac3cd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_titles_id'), table_name='titles')
    op.drop_index(op.f('ix_titles_tmdb_id'), table_name='titles')
    op.drop_table('titles')
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('watch_entries', sa.Column('media_item_id', sa.Integer(), nullable=True))
    op.add_column('watch_entries', sa.Column('tmdb_id', sa.Integer(), nullable=False))
    op.add_column('watch_entries', sa.Column('media_type', sa.String(), nullable=False))
    op.add_column('watch_entries', sa.Column('poster_path', sa.String(), nullable=True))
    op.add_column('watch_entries', sa.Column('status', sa.String(), nullable=False))
    op.add_column('watch_entries', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('watch_entries', sa.Column('is_private', sa.Boolean(), nullable=False))
    op.alter_column('watch_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_watch_entries_title_id'), table_name='watch_entries')
    op.drop_index(op.f('ix_watch_entries_user_id'), table_name='watch_entries')
    op.drop_constraint(op.f('uq_user_title'), 'watch_entries', type_='unique')
    op.create_index(op.f('ix_watch_entries_media_item_id'), 'watch_entries', ['media_item_id'], unique=False)
    op.create_index(op.f('ix_watch_entries_tmdb_id'), 'watch_entries', ['tmdb_id'], unique=False)
    op.create_unique_constraint('uq_watch_entry_user_title', 'watch_entries', ['user_id', 'tmdb_id', 'media_type'])
    op.drop_constraint(op.f('watch_entries_title_id_fkey'), 'watch_entries', type_='foreignkey')
    op.drop_constraint(op.f('watch_entries_user_id_fkey'), 'watch_entries', type_='foreignkey')
    op.create_foreign_key(None, 'watch_entries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'watch_entries', 'media_items', ['media_item_id'], ['id'], ondelete='SET NULL')
    op.drop_column('watch_entries', 'updated_at')
    op.drop_column('watch_entries', 'title_id')
    op.drop_column('watch_entries', 'review_text')
    op.drop_column('watch_entries', 'watched_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_entries', sa.Column('watched_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('watch_entries', sa.Column('review_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('watch_entries', sa.Column('title_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('watch_entries', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'watch_entries', type_='foreignkey')
    op.drop_constraint(None, 'watch_entries', type_='foreignkey')
    op.create_foreign_key(op.f('watch_entries_user_id_fkey'), 'watch_entries', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('watch_entries_title_id_fkey'), 'watch_entries', 'titles', ['title_id'], ['id'])
    op.drop_constraint('uq_watch_entry_user_title', 'watch_entries', type_='unique')
    op.drop_index(op.f('ix_watch_entries_tmdb_id'), table_name='watch_entries')
    op.drop_index(op.f('ix_watch_entries_media_item_id'), table_name='watch_entries')
    op.create_unique_constraint(op.f('uq_user_title'), 'watch_entries', ['user_id', 'title_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_watch_entries_user_id'), 'watch_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_watch_entries_title_id'), 'watch_entries', ['title_id'], unique=False)
    op.alter_column('watch_entries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('watch_entries', 'is_private')
    op.drop_column('watch_entries', 'notes')
    op.drop_column('watch_entries', 'status')
    op.drop_column('watch_entries', 'poster_path')
    op.drop_column('watch_entries', 'media_type')
    op.drop_column('watch_entries', 'tmdb_id')
    op.drop_column('watch_entries', 'media_item_id')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    op.create_table('titles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('release_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('poster_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('overview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('genres', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cached_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('titles_pkey')),
    sa.UniqueConstraint('tmdb_id', 'media_type', name=op.f('uq_tmdb_id_media_type'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_titles_tmdb_id'), 'titles', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_titles_id'), 'titles', ['id'], unique=False)
    # ### end Alembic commands ###
